name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # This runs the job every hour
  workflow_dispatch:      # This allows you to run the job manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: the-original-owner-username # Replace with the username of the original repository's owner
          base: main  # Replace with the branch you want to sync from (e.g., master, main)
          head: main  # Replace with the branch you want to sync to
